# Use Node for building
FROM node:20-alpine as builder

WORKDIR /app
COPY ../frontend /app
RUN npm install && npm run build

# Use NGINX for serving static files
FROM nginx:alpine

# Clean up default nginx config (optional)
RUN rm -rf /usr/share/nginx/html/*

COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
